GET http://localhost:5000

### Verify user Route
GET http://localhost:5000/api/auth/verifyuser


### refresh token
GET http://localhost:5000/api/auth/refreshtoken/

### login route
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "testtest"
}


### get projects
GET http://localhost:5000/api/app/projects/

### add project 
POST http://localhost:5000/api/app/project/
Content-Type: application/json

{
    "title": "Faded"
}
### delete project 
DELETE http://localhost:5000/api/app/project/5f717cd8b36f752bb83682ba


### add task 
POST http://localhost:5000/api/app/project/5fa16174e49a2f266ca2ac72/task
Content-Type: application/json

{
    "note": "Task 6",
    "status": "done"
}


### edit task 
PUT http://localhost:5000/api/app/task/5f71db5dca03a43498679505
Content-Type: application/json

{
    "status": "in-progress"
}

### delete task 
DELETE http://localhost:5000/api/app/task/5f71db5dca03a43498679505



### register route
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Abir321",
    "email": "abir321@test.com",
    "password": "testtest"
}


### logout route
DELETE http://localhost:5000/api/auth/logout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9 eyJpYXQiOjE2MDEyMDkyMTUsImV4cCI6MTYzMjc2NjgxNSwiYXVkIjoiNWY2ZjMxZWY5YjVmM2QxYWM4OGQ3ODlmIiwiaXNzIjoicGFyc2Ftb3JzaGVkLm5ldGxpZnkuYXBwIn0.ztYtkTLm7xpK32KV_cX-QJtdxnx_50cFb07Vzo76d40